# Generated by Django 5.0.6 on 2024-05-09 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('real', models.FloatField()),
                ('imaginary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NumberArray',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numbers', models.TextField()),
            ],
        ),
    ]
